language: python
python:
  - "2.7"
# command to install dependencies
install:
  - deactivate
  - virtualenv .
  - python setup.py develop
# command to run tests
script:
  - ./bin/build_one . build_everything

