language: python
python:
  - "2.7"
# command to install dependencies
install:
  - deactivate
  - virtualenv .
  - bin/python setup.py develop
# command to run tests
script:
  - ./bin/test_sample_projects

